//ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// AUTH
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//LOG OUT
export const LOGOUT = 'LOGOUT';

// PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// ACCOUNT
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// FLIGHTS
export const GET_FLIGHTS = 'GET_FLIGHTS';
export const FLIGHTS_ERROR = 'FLIGHTS_ERROR';
export const GET_AIRPORT = 'GET_AIRPORT';

// WEATHER
export const GET_WEATHER = 'GET_WEATHER';
export const WEATHER_ERROR = 'WEATHER_ERROR';
